name: infoplus
description: Aplicativo Flutter InfoPlus - offline-first
version: 2.0.0+2

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '3.29.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.4                                  # ProxyProvider, select API 6

  # Code generation annotations
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

  # HTTP client
  http: ^0.14.0

  # Secure storage, local DB
  flutter_secure_storage: ^8.0.0
  sqflite: ^2.0.0+4
  connectivity_plus: ^3.0.3

  # Firebase Core & Auth
  firebase_core: ^3.13.0                            # Dart 3 compatível 7
  firebase_auth: ^5.5.2                             # Flutter ≥3.16, Dart ≥3.2 8

  # Firebase Firestore, Functions, Messaging
  cloud_firestore: ^5.6.6                           # Última versão FlutterFire 9
  cloud_functions: ^5.5.0                           # Plugin oficial para Cloud Functions 10
  firebase_messaging: ^15.2.5                       # FCM atualizado 11

  # Offline cache & utilities
  drift: ^2.0.0
  path_provider: ^2.0.0
  flutter_dotenv: ^5.1.0
  intl: ^0.18.1
  permission_handler: ^11.3.0

  # Localization & icons
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  freezed: ^2.4.0
  json_serializable: ^6.6.0
  drift_dev: ^2.0.0
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700