name: infoplus
description: Aplicativo Flutter InfoPlus - offline-first
version: 2.0.0+2

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '3.29.0'

dependencies:
  flutter:
    sdk: flutter

  # Gerenciamento de estado
  provider: ^6.1.4

  # Anotações para geração de código
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

  # HTTP cliente
  http: ^1.4.0

  # Armazenamento e cache local
  flutter_secure_storage: ^8.0.0
  sqflite: ^2.0.0+4
  connectivity_plus: ^3.0.3

  # FlutterFire Core & Auth
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2

  # Firestore, Functions e Messaging
  cloud_firestore: ^5.6.6
  cloud_functions: ^5.5.0
  firebase_messaging: ^15.2.5

  # Banco local com Drift
  drift: ^2.0.0
  path_provider: ^2.0.0

  # Variáveis de ambiente
  flutter_dotenv: ^5.1.0

  # Internacionalização
  intl: ^0.19.0

  # Permissões
  permission_handler: ^11.3.0

  # Localizações e ícones
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  freezed: ^2.4.0
  json_serializable: ^6.6.0
  drift_dev: ^2.0.0
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700