name: CI Flutter ─ Test & Debug APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Cache de pacotes pub
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Configurar Flutter (estável)
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Verificar versão
        run: flutter --version

      # 1) Regenera a pasta Android com embedding v2
      - name: Remover diretório Android antigo
        run: rm -rf android/                                  # elimina v1 embedding 2

      - name: Gerar plataforma Android (embedding v2)
        run: flutter create . --platforms=android            # cria Android v2 3

      # 2) Reaplica customizações no build.gradle via sed
      - name: Aplicar sed em android/app/build.gradle
        run: |
          # Insere namespace e ndkVersion logo após compileSdkVersion
          sed -i "/compileSdkVersion 33/a \ \ \ \ namespace 'com.ussd.infoplus'\n\ \ \ \ ndkVersion \"27.0.12077973\"" android/app/build.gradle
          # Atualiza minSdkVersion para 23
          sed -i "s/minSdkVersion 21/minSdkVersion 23/" android/app/build.gradle

      - name: Instalar dependências
        run: flutter pub get

      - name: Gerar código (build_runner)
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Executar testes unitários
        run: flutter test

      - name: Adicionar google-services.json
        run: |
          mkdir -p android/app
          echo "${{ secrets.FIREBASE_ANDROID_JSON }}" > android/app/google-services.json

      - name: Compilar APK Debug
        run: flutter build apk --debug

      - name: Upload do APK Debug
        uses: actions/upload-artifact@v4
        with:
          name: infoplus-debug-${{ matrix.os }}
          path: build/app/outputs/flutter-apk/app-debug.apk