name: Build APK (debug unsigned)

on:
  push:
    branches: [main]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Instalar Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'

    - name: Instalar dependências
      run: flutter pub get

    - name: Adicionar google-services.json
      run: |
        mkdir -p android/app
        echo "${{ secrets.FIREBASE_ANDROID_JSON }}" > android/app/google-services.json

    - name: Compilar APK (debug)
      run: flutter build apk --debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: infoplus-debug-apk
        path: build/app/outputs/flutter-apk/app-debug.apk